import type { StatsTemplateRecord } from '../templateTypes'

const PREMIUM_TEMPLATE_LAYOUT = [
  {
    type: 'textTitle',
    title: 'Titre',
    x: 420,
    y: 210,
    w: 2850,
    h: 150,
    props: {
      content: 'Performance commerciale',
      align: 'left',
      fontSize: 70,
      color: '#0f172a',
      autoHeight: true,
    },
  },
  {
    type: 'textBlock',
    title: 'Sous-titre',
    x: 420,
    y: 356,
    w: 2850,
    h: 150,
    props: {
      content:
        'Vue executive hebdomadaire. Le template priorise la lisibilite, la hierarchie et les decisions actionnables.',
      align: 'left',
      fontSize: 24,
      color: '#334155',
      autoHeight: true,
    },
  },
  {
    type: 'grossRevenue',
    title: "Chiffre d'affaires",
    x: 420,
    y: 548,
    w: 690,
    h: 240,
    props: { view: 'number', bucket: 'week', autoHeight: false },
  },
  {
    type: 'netProfit',
    title: 'Profit net',
    x: 1140,
    y: 548,
    w: 690,
    h: 240,
    props: { view: 'number', bucket: 'week', autoHeight: false },
  },
  {
    type: 'avgMargin',
    title: 'Marge',
    x: 1860,
    y: 548,
    w: 690,
    h: 240,
    props: { autoHeight: false },
  },
  {
    type: 'roi',
    title: 'ROI',
    x: 2580,
    y: 548,
    w: 690,
    h: 240,
    props: { autoHeight: false },
  },
  {
    type: 'netProfit',
    title: 'Tendance 30 jours',
    x: 420,
    y: 818,
    w: 1880,
    h: 640,
    props: {
      view: 'line',
      bucket: 'week',
      showArea: true,
      showComparison: true,
      autoHeight: false,
    },
  },
  {
    type: 'topProfitDrivers',
    title: "Points d'attention",
    x: 2330,
    y: 818,
    w: 940,
    h: 640,
    props: { view: 'bars', top: 8, autoHeight: false },
  },
  {
    type: 'topSales',
    title: 'Top ventes',
    x: 420,
    y: 1488,
    w: 1410,
    h: 360,
    props: { limit: 8, autoHeight: false },
  },
  {
    type: 'brands',
    title: 'Repartition marques',
    x: 1860,
    y: 1488,
    w: 690,
    h: 360,
    props: { top: 7, autoHeight: false },
  },
  {
    type: 'textBlock',
    title: 'Actions prioritaires',
    x: 2580,
    y: 1488,
    w: 690,
    h: 360,
    props: {
      content:
        'Actions prioritaires\n1. Renforcer les meilleures marges.\n2. Corriger les canaux sous cible.\n3. Proteger le cash sur les references lentes.',
      align: 'left',
      fontSize: 20,
      color: '#0f172a',
      autoHeight: true,
    },
  },
] as const

export const POWERBOARD_PREMIUM_TEMPLATE: StatsTemplateRecord = {
  id: 'sys_template_powerboard_premium',
  source: 'system',
  name: 'Template premium PowerBoard',
  description:
    'Composition editoriale plein ecran inspiree Canva + Power BI: hero, KPIs, tendance, analyse et actions.',
  category: 'Premium',
  tags: ['powerbi', 'canva', 'executive', 'clean'],
  accent: '#0ea5e9',
  density: 'balanced',
  sortRank: 1,
  recommendedRange: { kind: 'month' },
  themeTokenId: 'executive_cobalt',
  scene: {
    id: 'scene_powerboard_premium',
    boardBackground:
      'linear-gradient(180deg, rgba(243, 248, 255, 0.98) 0%, rgba(236, 244, 255, 0.98) 100%), radial-gradient(circle at 8% 0%, rgba(14, 165, 233, 0.14), transparent 38%), radial-gradient(circle at 92% 0%, rgba(2, 132, 199, 0.12), transparent 36%)',
    boardBackgroundLight:
      'linear-gradient(180deg, rgba(246, 250, 255, 0.98) 0%, rgba(237, 245, 255, 0.98) 100%), radial-gradient(circle at 8% 0%, rgba(14, 165, 233, 0.14), transparent 38%), radial-gradient(circle at 92% 0%, rgba(2, 132, 199, 0.12), transparent 36%)',
  },
  layout: [...PREMIUM_TEMPLATE_LAYOUT],
}
